const $ = (id) => document.getElementById(id);
const meta = { AAPL:{name:'Apple Inc.',venue:'NASDAQ',base:184,drift:.00075,vol:.015}, MSFT:{name:'Microsoft Corp.',venue:'NASDAQ',base:420,drift:.00065,vol:.012}, NVDA:{name:'NVIDIA Corp.',venue:'NASDAQ',base:118,drift:.00115,vol:.026}, TSLA:{name:'Tesla Inc.',venue:'NASDAQ',base:190,drift:.00025,vol:.032}, RELIANCE:{name:'Reliance Industries',venue:'NSE',base:2925,drift:.00048,vol:.013} };
let state = { symbol:'AAPL', data:[], model:null, horizon:14, lambda:.18, custom:false };
function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function normal(rand){let u=rand()||.01,v=rand()||.01;return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function businessDate(offset){const d=new Date('2024-06-21T12:00:00');let left=offset;while(left>0){d.setDate(d.getDate()-1);if(d.getDay()>0&&d.getDay()<6)left--}return d.toISOString().slice(0,10)}
function sampleData(symbol){const m=meta[symbol], random=rng(hash(symbol));let price=m.base*.78, out=[];for(let i=0;i<320;i++){let cyc=.0024*Math.sin(i/18)+.0015*Math.cos(i/47), shock=normal(random)*m.vol;price*=1+m.drift+cyc+shock;price=Math.max(price,m.base*.38);out.push({date:businessDate(319-i),close:+price.toFixed(2)});}return out}
function mean(a){return a.reduce((s,v)=>s+v,0)/a.length}function std(a){let m=mean(a);return Math.sqrt(mean(a.map(v=>(v-m)**2)))||1}
function sma(prices,n){return mean(prices.slice(-n))}function rsi(prices,n=14){let gains=0,losses=0;for(let i=prices.length-n;i<prices.length;i++){let d=prices[i]-prices[i-1];gains+=Math.max(0,d);losses+=Math.max(0,-d)}let rs=(gains/n)/((losses/n)||.0001);return 100-(100/(1+rs))}
function features(prices){let now=prices.at(-1), s5=sma(prices,5),s14=sma(prices,14),mom=(now/prices.at(-6)-1)*100,returns=[];for(let i=prices.length-5;i<prices.length;i++)returns.push(prices[i]/prices[i-1]-1);return [now,s5,s14,rsi(prices),mom,std(returns)*100]}
function dot(a,b){return a.reduce((s,v,i)=>s+v*b[i],0)}
function train(data,lambda){let rows=[];for(let i=20;i<data.length-1;i++){let closes=data.slice(0,i+1).map(d=>d.close);rows.push({x:features(closes),y:data[i+1].close})}let cut=Math.floor(rows.length*.8), trainRows=rows.slice(0,cut),test=rows.slice(cut);let cols=trainRows[0].x.length, means=Array.from({length:cols},(_,j)=>mean(trainRows.map(r=>r.x[j]))),scales=Array.from({length:cols},(_,j)=>std(trainRows.map(r=>r.x[j]))),yMean=mean(trainRows.map(r=>r.y));let X=trainRows.map(r=>r.x.map((v,j)=>(v-means[j])/scales[j])),Y=trainRows.map(r=>r.y-yMean),w=Array(cols).fill(0),rate=.035;for(let epoch=0;epoch<1700;epoch++){let grad=Array(cols).fill(0);for(let i=0;i<X.length;i++){let err=dot(w,X[i])-Y[i];for(let j=0;j<cols;j++)grad[j]+=err*X[i][j]}for(let j=0;j<cols;j++)w[j]-=rate*((2/X.length)*grad[j]+2*lambda*w[j])}let predict=(x)=>yMean+dot(w,x.map((v,j)=>(v-means[j])/scales[j]));let actual=test.map(r=>r.y),predicted=test.map(r=>predict(r.x)), errs=actual.map((y,i)=>y-predicted[i]), rmse=Math.sqrt(mean(errs.map(e=>e*e))),mae=mean(errs.map(Math.abs)), r2=1-errs.reduce((s,e)=>s+e*e,0)/actual.reduce((s,y)=>s+(y-mean(actual))**2,0);let impacts=w.map((v,j)=>Math.abs(v/scales[j]));return {predict,rmse,mae,r2,impacts,validation:test.length}}
function forecast(){let m=train(state.data,state.lambda), prices=state.data.map(d=>d.close), forecast=[];for(let i=0;i<state.horizon;i++){let next=Math.max(1,m.predict(features(prices)));prices.push(next);forecast.push(next)}state.model={...m,forecast};render();}
function money(v){let prefix=state.symbol==='RELIANCE'?'₹':'$';return prefix+v.toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:2})}
function linePath(vals,scale,x0,x1){return vals.map((v,i)=>`${i?'L':'M'} ${(x0+(x1-x0)*i/(vals.length-1)).toFixed(1)} ${scale(v).toFixed(1)}`).join(' ')}
function renderChart(){let hist=state.data.slice(-70).map(d=>d.close),fc=state.model.forecast,all=[...hist,...fc],min=Math.min(...all)*.985,max=Math.max(...all)*1.015,w=760,h=268,p={l:6,r:6,t:15,b:25},scale=v=>p.t+(max-v)/(max-min)*(h-p.t-p.b),split=p.l+(w-p.l-p.r)*(hist.length-1)/(all.length-1),histPath=linePath(hist,scale,p.l,split),forecastPath=linePath([hist.at(-1),...fc],scale,split,w-p.r), upper=fc.map((v,i)=>v+state.model.rmse*(1.15+i*.12)),lower=fc.map((v,i)=>v-state.model.rmse*(1.15+i*.12)),upperPath=linePath([hist.at(-1),...upper],scale,split,w-p.r),lowerPath=linePath([hist.at(-1),...lower].reverse(),scale,w-p.r,split);let ticks=[0,.5,1].map(k=>min+(max-min)*k);$('priceChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img"><defs><linearGradient id="historyGradient" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#315a4d" stop-opacity=".15"/><stop offset="1" stop-color="#315a4d" stop-opacity="0"/></linearGradient></defs>${ticks.map(v=>`<line class="gridline" x1="${p.l}" x2="${w-p.r}" y1="${scale(v)}" y2="${scale(v)}"/><text class="axis-label" x="${w-3}" y="${scale(v)-5}" text-anchor="end">${money(v)}</text>`).join('')}<path class="area-history" d="${histPath} L ${split} ${h-p.b} L ${p.l} ${h-p.b} Z"/><path class="confidence-area" d="${upperPath} L ${lowerPath} Z"/><line x1="${split}" x2="${split}" y1="${p.t}" y2="${h-p.b}" stroke="#d8d4cb" stroke-dasharray="3 3"/><path class="history-line" d="${histPath}"/><path class="forecast-line" d="${forecastPath}"/><circle cx="${split}" cy="${scale(hist.at(-1))}" r="4" fill="#315a4d" stroke="#fffdf8" stroke-width="2"/><text class="axis-label" x="${p.l}" y="${h-4}">${hist.length} SESSIONS AGO</text><text class="axis-label" x="${w-p.r}" y="${h-4}" text-anchor="end">PROJECTED</text></svg>`}
function render(){let last=state.data.at(-1),prev=state.data.at(-2),model=state.model,projected=model.forecast.at(-1), change=(last.close/prev.close-1)*100,projectChange=(projected/last.close-1)*100, profile=meta[state.symbol]||{name:'Uploaded series',venue:'CSV'};$('tickerLabel').textContent=`${state.symbol} / ${profile.venue}`;$('latestPrice').textContent=money(last.close);$('priceChange').textContent=`${change>=0?'+':''}${change.toFixed(2)}% today`;$('priceChange').className=change>=0?'positive':'negative';$('lastDate').textContent=`Last observation · ${new Date(last.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}`;$('forecastLabel').textContent=`${state.horizon}-session projection`;$('horizonNumber').textContent=state.horizon;$('projectedPrice').textContent=money(projected);$('projectedChange').textContent=`${projectChange>=0?'+':''}${projectChange.toFixed(2)}% from last close`;$('rmse').textContent=money(model.rmse);$('mae').textContent=money(model.mae);$('r2').textContent=Math.max(-.99,model.r2).toFixed(2);$('validationNote').textContent=`${model.validation} validation sessions analysed`;$('confidenceText').textContent=`± ${money(model.rmse*(1.15+(state.horizon-1)*.12))}`;$('confidenceFill').style.width=`${Math.max(28,79-state.horizon*1.15)}%`;let bullish=projectChange>=0;$('signalTitle').textContent=bullish?'Cautiously bullish':'Defensive outlook';$('signalCopy').textContent=bullish?'The projected trend holds above its 14-day average, though the confidence band widens with time.':'The model detects downward pressure in the near-term trend; uncertainty widens further out.';let labels=['Latest close','5-day average','14-day average','RSI (14)','5-day momentum','Realized volatility'];let maxImpact=Math.max(...model.impacts);$('featureList').innerHTML=labels.map((label,i)=>`<div class="feature-row"><label>${label}</label><span class="feature-track"><i style="width:${(model.impacts[i]/maxImpact*100).toFixed(0)}%"></i></span><b>${(model.impacts[i]/maxImpact*100).toFixed(0)}%</b></div>`).join('');renderChart()}
function run(){state.horizon=+$('horizonSelect').value;state.lambda=+$('regularization').value;$('lambdaOutput').textContent=state.lambda.toFixed(2);let btn=$('runModelBtn');btn.querySelector('span').textContent='Training…';btn.disabled=true;setTimeout(()=>{forecast();btn.querySelector('span').textContent='Run model';btn.disabled=false},180)}
$('runModelBtn').addEventListener('click',run);$('horizonSelect').addEventListener('change',run);$('regularization').addEventListener('input',e=>{$('lambdaOutput').textContent=(+e.target.value).toFixed(2)});$('stockSelect').addEventListener('change',e=>{state.symbol=e.target.value;state.data=sampleData(state.symbol);state.custom=false;run()});$('aboutBtn').addEventListener('click',()=>$('aboutDialog').showModal());$('closeDialog').addEventListener('click',()=>$('aboutDialog').close());$('csvUpload').addEventListener('change',async e=>{let f=e.target.files[0];if(!f)return;let text=await f.text(),rows=text.trim().split(/\r?\n/),heads=rows.shift().split(',').map(x=>x.trim().toLowerCase()),dateI=heads.indexOf('date'),closeI=heads.indexOf('close');if(dateI<0||closeI<0){alert('Please upload a CSV with Date and Close columns.');return}let parsed=rows.map(r=>r.split(',')).map(r=>({date:r[dateI],close:+r[closeI]})).filter(r=>r.date&&Number.isFinite(r.close)).sort((a,b)=>a.date.localeCompare(b.date));if(parsed.length<50){alert('Please include at least 50 valid rows.');return}state.symbol='YOUR DATA';state.data=parsed;state.custom=true;run()});
state.data=sampleData(state.symbol);forecast();
